# Generated by Django 4.0.5 on 2022-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendidos_mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendidos_mes',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='soma_valores',
            table='soma_valores',
        ),
    ]
